-- MySQL Script generated by MySQL Workbench
-- Thu Oct  7 10:15:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema demkovych_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demkovych_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demkovych_db` DEFAULT CHARACTER SET utf8 ;
USE `demkovych_db` ;

-- -----------------------------------------------------
-- Table `demkovych_db`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`country` (
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`library` (
  `id` INT NOT NULL,
  `amount_of_liked_songs` INT NULL,
  `amount_of_downloaded_songs` INT NULL,
  `amount_of_liked_albums` INT NULL,
  `amount_of_donwloaded_albums` INT NULL,
  `amount_of_susbscribed_artists` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`gender` (
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `age` INT NOT NULL,
  `birthday` VARCHAR(45) NULL,
  `mobile_number` INT NULL,
  `country_name` VARCHAR(40) NOT NULL,
  `library_id` INT NOT NULL,
  `playlist_id` INT NULL,
  `gender_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `library_id_UNIQUE` () VISIBLE,
  INDEX `fk_user_country1_idx` (`country_name` ASC) VISIBLE,
  INDEX `fk_user_library1_idx` (`library_id` ASC) VISIBLE,
  INDEX `fk_user_gender1_idx` (`gender_type` ASC) VISIBLE,
  CONSTRAINT `fk_user_country1`
    FOREIGN KEY (`country_name`)
    REFERENCES `demkovych_db`.`country` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_library1`
    FOREIGN KEY (`library_id`)
    REFERENCES `demkovych_db`.`library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_gender1`
    FOREIGN KEY (`gender_type`)
    REFERENCES `demkovych_db`.`gender` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`security`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`security` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_security_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `demkovych_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`singer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`singer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `amount_of_albums` INT NULL,
  `amount_of_songs` INT NULL,
  `mounthly_listeners` INT NOT NULL,
  `country_name` VARCHAR(40) NOT NULL,
  `gender_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_singer_country1_idx` (`country_name` ASC) VISIBLE,
  INDEX `fk_singer_gender1_idx` (`gender_type` ASC) VISIBLE,
  CONSTRAINT `fk_singer_country1`
    FOREIGN KEY (`country_name`)
    REFERENCES `demkovych_db`.`country` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_singer_gender1`
    FOREIGN KEY (`gender_type`)
    REFERENCES `demkovych_db`.`gender` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `release_year` INT NOT NULL,
  `amount_of_song` INT NOT NULL,
  `total_time_of_listeting` INT NULL,
  `amount_of_likes` INT NULL,
  `singer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_singer1_idx` (`singer_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_singer1`
    FOREIGN KEY (`singer_id`)
    REFERENCES `demkovych_db`.`singer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`language` (
  `languade` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`languade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `time` DATETIME NULL,
  `likes` INT NULL,
  `downloaded` INT NULL,
  `feat(with)` VARCHAR(45) NULL,
  `streaming` INT NULL,
  `album_id` INT NOT NULL,
  `language_languade` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_song_album1_idx` (`album_id` ASC) VISIBLE,
  INDEX `fk_song_language1_idx` (`language_languade` ASC) VISIBLE,
  CONSTRAINT `fk_song_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `demkovych_db`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_language1`
    FOREIGN KEY (`language_languade`)
    REFERENCES `demkovych_db`.`language` (`languade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demkovych_db`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demkovych_db`.`playlist` (
  `id` INT NOT NULL,
  `appointment` VARCHAR(45) NOT NULL,
  `some_text` VARCHAR(45) NOT NULL,
  `amount_of_songs` INT NULL,
  `amount_of_liked` INT NULL,
  `total_time_of_listening` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_playlist_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `demkovych_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
